---
title: "Calorie and Macronutrient Calculator"
author: "Tyler Clark"
format:
  html:
    page-layout: custom
server: shiny
---

```{r}
#| label: sidebar-input
#| panel: sidebar

selectInput("sex", "Sex:", c("Male", "Female"))
  
numericInput("age", "Age:", min = 1, max = 100, value = 30, step=1)
numericInput("bodyWeight", "Weight:", min=1, max=500, value=150, step=1)

numericInput("feet", "Feet:", min=0, max=8, value=5, step=1)
numericInput("inches", "Inches:", min=0, max=11, value=6, step=1)

selectInput("multiplier", "Activity Level:",
            c("Basal Metabolic Rate"=1,
              "Sedentary: little to no exercise"=1.2,
              "Light: exercise 1-3 times per week"=1.375,
              "Moderate: exercise 4-5 times/week"=1.465, 
              "Active: daily exercise or intense exercise 3-4 times per week"=1.55,
              "Very Active: intense exercise 6-7 times per week"=1.726, 
              "Extra Active: very intense exercise daily, or physical job"=1.90))

# Exercise: 15-30 minutes of elevated heart rate activity.
# Intense exercise: 45-120 minutes of elevated heart rate activity.
# Very intense exercise: 2+ hours of elevated heart rate activity.

```

```{r}
#| label: results-output
#| panel: fill
#| layout-ncol: 2

tableOutput("tableCalories")
tableOutput("tableMacros")
```

```{r}
#| label: BMR-calculations
#| context: server

wtKg <- reactive(input$bodyWeight * 0.453592)
htCm <- reactive((input$feet * 12 + input$inches) * 2.54)

# Mifflin-St Jeor Equation:
msj <- reactive(
  if(input$sex == "Male"){
    10 * wtKg() + 6.25 * htCm() - 5 * input$age + 5
  } else {
    10 * wtKg() + 6.25 * htCm() - 5 * input$age - 161
  }
)

# Revised Harris-Benedict Equation:
rhb <- reactive(
  if(input$sex == "Male"){
    13.397 * wtKg() + 4.799 * htCm() - 5.677 * input$age + 88.362
  } else{
    9.247 * wtKg() + 3.098 * htCm() - 4.330 * input$age + 447.593
  }
)


# Katch-McArdle Formula:
kma <- reactive(
  370 + 21.6 * (1-0.2) * wtKg()
)

# Activity Multiplier
multFac <- reactive(as.numeric(input$multiplier))

```


```{r}
#| label: table-calories
#| context: server

output$tableCalories <- renderTable({
  list("MSJ" = round(msj()*multFac(), 0),
       "RHB" = round(rhb()*multFac(), 0),
       "KMA" = round(kma()*multFac(), 0))
})
```


```{r}
#| label: table-macronutrients
#| context: server
output$tableMacros <- renderTable({
  list("Protein" = 0.25,
         "Fat" = 0.25,
         "Carbs" = 0.5)
})
```

